### ISSUE TITLE
独创性声明是啥

### ISSUE THREAD

**Issue by liangzhenduo** [Checkmate986212/TJU-Thesis-2020#1]
RT 之前好像没有这页

**Comment by HeliosZhao** [comment]
我是从毕设官网下的，2019年11月发的版本，最新的是有这个的。

**Comment by liangzhenduo** [comment]
还有预览的参考文献没编译出来

**Comment by HeliosZhao** [comment]
预览的参考文献是因为我把关于江泽民的参考文献在ref.bib里删除了，所以没编译。你在自己用的时候，把参考文献放到ref.bib里编译即可
